name: Template Backend CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Change Directory
        run: cd /home/template/template-runner/_work/template/template

      - name: Restart PM2 Process
        run: pm2 restart 0
